apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xkappel/ambulance-ufe
    newName: xkappel/ambulance-ufe
    newTag: 1.1.0 # aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
  - name: xkappel/ambulance-wl-webapi
    newName: xkappel/ambulance-wl-webapi
    newTag: 1.1.0

replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: xkappel-ambulance-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: xkappel-ambulance-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ':'
        index: 1
