apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xkappel/ambulance-wl-webapi
    newName: xkappel/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
    newTag: main.20240325.2147 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
  - name: xkappel/ambulance-ufe
    newName: xkappel/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20240305.0806 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
  - name: milung/ufe-controller
    newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
    newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
