apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/part-of: wac-hospital
  app.kubernetes.io/name: xkappel-ambulance-wl

resources:
  - ../../../apps/xkappel-ambulance-ufe
  - ../../../apps/xkappel-ambulance-webapi

components:
  - ../../../components/version-release
