apiVersion: apps/v1
kind: Deployment
metadata:
  name: xkappel-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /xkappel-openapi
            - name: BASE_URL
              value: /xkappel-openapi-ui
